-- Necesario para poder crear usuarios --
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Creacion de usuario --
CREATE USER DEVELOPER IDENTIFIED BY "C0n3x10n*"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- Permisos --
GRANT "CONNECT" TO DEVELOPER;
GRANT ALTER TABLESPACE TO DEVELOPER;
GRANT EXECUTE ANY PROCEDURE TO DEVELOPER;