//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class Cliente : object
    {
        
        private string ApellidosField;
        
        private string DireccionField;
        
        private string IdClienteField;
        
        private string NombresField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mesero", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class Mesero : object
    {
        
        private int AntiguedadField;
        
        private string ApellidosField;
        
        private int EdadField;
        
        private string IdMeseroField;
        
        private string NombresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Antiguedad
        {
            get
            {
                return this.AntiguedadField;
            }
            set
            {
                this.AntiguedadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad
        {
            get
            {
                return this.EdadField;
            }
            set
            {
                this.EdadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdMesero
        {
            get
            {
                return this.IdMeseroField;
            }
            set
            {
                this.IdMeseroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mesa", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class Mesa : object
    {
        
        private string NombreField;
        
        private int NroMesaField;
        
        private int PuestosField;
        
        private string ReservadaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroMesa
        {
            get
            {
                return this.NroMesaField;
            }
            set
            {
                this.NroMesaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puestos
        {
            get
            {
                return this.PuestosField;
            }
            set
            {
                this.PuestosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reservada
        {
            get
            {
                return this.ReservadaField;
            }
            set
            {
                this.ReservadaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supervisor", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class Supervisor : object
    {
        
        private string ApellidosField;
        
        private int EdadField;
        
        private string IdSupervisorField;
        
        private string NombresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad
        {
            get
            {
                return this.EdadField;
            }
            set
            {
                this.EdadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSupervisor
        {
            get
            {
                return this.IdSupervisorField;
            }
            set
            {
                this.IdSupervisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class Factura : object
    {
        
        private string ApellidosField;
        
        private string DireccionField;
        
        private string IdClienteField;
        
        private int IdMeseroField;
        
        private string NombresField;
        
        private int NroMesaField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMesero
        {
            get
            {
                return this.IdMeseroField;
            }
            set
            {
                this.IdMeseroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroMesa
        {
            get
            {
                return this.NroMesaField;
            }
            set
            {
                this.NroMesaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallexFactura", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class DetallexFactura : object
    {
        
        private string IdSupervisorField;
        
        private int NroFacturaField;
        
        private string PlatoField;
        
        private int ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSupervisor
        {
            get
            {
                return this.IdSupervisorField;
            }
            set
            {
                this.IdSupervisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroFactura
        {
            get
            {
                return this.NroFacturaField;
            }
            set
            {
                this.NroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plato
        {
            get
            {
                return this.PlatoField;
            }
            set
            {
                this.PlatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentasMesero", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class VentasMesero : object
    {
        
        private string ApellidosField;
        
        private string IdMeseroField;
        
        private string NombresField;
        
        private int TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdMesero
        {
            get
            {
                return this.IdMeseroField;
            }
            set
            {
                this.IdMeseroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsumosClientes", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class ConsumosClientes : object
    {
        
        private string ApellidosField;
        
        private string IdClienteField;
        
        private string NombresField;
        
        private int ValorConsumoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValorConsumo
        {
            get
            {
                return this.ValorConsumoField;
            }
            set
            {
                this.ValorConsumoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoTop", Namespace="http://schemas.datacontract.org/2004/07/ComidasDelSur_WS.Models")]
    public partial class ProductoTop : object
    {
        
        private int CantidadField;
        
        private string PeriodoField;
        
        private string PlatoField;
        
        private int ValorTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Periodo
        {
            get
            {
                return this.PeriodoField;
            }
            set
            {
                this.PeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plato
        {
            get
            {
                return this.PlatoField;
            }
            set
            {
                this.PlatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValorTotal
        {
            get
            {
                return this.ValorTotalField;
            }
            set
            {
                this.ValorTotalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestauranteService.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarCliente", ReplyAction="http://tempuri.org/IService/RegistrarClienteResponse")]
        string RegistrarCliente(RestauranteService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarCliente", ReplyAction="http://tempuri.org/IService/RegistrarClienteResponse")]
        System.Threading.Tasks.Task<string> RegistrarClienteAsync(RestauranteService.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarMesero", ReplyAction="http://tempuri.org/IService/RegistrarMeseroResponse")]
        string RegistrarMesero(RestauranteService.Mesero mesero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarMesero", ReplyAction="http://tempuri.org/IService/RegistrarMeseroResponse")]
        System.Threading.Tasks.Task<string> RegistrarMeseroAsync(RestauranteService.Mesero mesero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarMesa", ReplyAction="http://tempuri.org/IService/RegistrarMesaResponse")]
        string RegistrarMesa(RestauranteService.Mesa mesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarMesa", ReplyAction="http://tempuri.org/IService/RegistrarMesaResponse")]
        System.Threading.Tasks.Task<string> RegistrarMesaAsync(RestauranteService.Mesa mesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarSupervisor", ReplyAction="http://tempuri.org/IService/RegistrarSupervisorResponse")]
        string RegistrarSupervisor(RestauranteService.Supervisor supervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RegistrarSupervisor", ReplyAction="http://tempuri.org/IService/RegistrarSupervisorResponse")]
        System.Threading.Tasks.Task<string> RegistrarSupervisorAsync(RestauranteService.Supervisor supervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultaSupervisor", ReplyAction="http://tempuri.org/IService/ConsultaSupervisorResponse")]
        string ConsultaSupervisor(int IdSupervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConsultaSupervisor", ReplyAction="http://tempuri.org/IService/ConsultaSupervisorResponse")]
        System.Threading.Tasks.Task<string> ConsultaSupervisorAsync(int IdSupervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarMesero", ReplyAction="http://tempuri.org/IService/ActualizarMeseroResponse")]
        string ActualizarMesero(RestauranteService.Mesero mesero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarMesero", ReplyAction="http://tempuri.org/IService/ActualizarMeseroResponse")]
        System.Threading.Tasks.Task<string> ActualizarMeseroAsync(RestauranteService.Mesero mesero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarMesa", ReplyAction="http://tempuri.org/IService/ActualizarMesaResponse")]
        string ActualizarMesa(RestauranteService.Mesa mesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarMesa", ReplyAction="http://tempuri.org/IService/ActualizarMesaResponse")]
        System.Threading.Tasks.Task<string> ActualizarMesaAsync(RestauranteService.Mesa mesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarSupervisor", ReplyAction="http://tempuri.org/IService/ActualizarSupervisorResponse")]
        string ActualizarSupervisor(RestauranteService.Supervisor supervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ActualizarSupervisor", ReplyAction="http://tempuri.org/IService/ActualizarSupervisorResponse")]
        System.Threading.Tasks.Task<string> ActualizarSupervisorAsync(RestauranteService.Supervisor supervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarMesero", ReplyAction="http://tempuri.org/IService/EliminarMeseroResponse")]
        string EliminarMesero(RestauranteService.Mesero mesero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarMesero", ReplyAction="http://tempuri.org/IService/EliminarMeseroResponse")]
        System.Threading.Tasks.Task<string> EliminarMeseroAsync(RestauranteService.Mesero mesero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarMesa", ReplyAction="http://tempuri.org/IService/EliminarMesaResponse")]
        string EliminarMesa(RestauranteService.Mesa mesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarMesa", ReplyAction="http://tempuri.org/IService/EliminarMesaResponse")]
        System.Threading.Tasks.Task<string> EliminarMesaAsync(RestauranteService.Mesa mesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarSupervisor", ReplyAction="http://tempuri.org/IService/EliminarSupervisorResponse")]
        string EliminarSupervisor(RestauranteService.Supervisor supervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminarSupervisor", ReplyAction="http://tempuri.org/IService/EliminarSupervisorResponse")]
        System.Threading.Tasks.Task<string> EliminarSupervisorAsync(RestauranteService.Supervisor supervisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMeseros", ReplyAction="http://tempuri.org/IService/GetMeserosResponse")]
        RestauranteService.Mesero[] GetMeseros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMeseros", ReplyAction="http://tempuri.org/IService/GetMeserosResponse")]
        System.Threading.Tasks.Task<RestauranteService.Mesero[]> GetMeserosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMesas", ReplyAction="http://tempuri.org/IService/GetMesasResponse")]
        RestauranteService.Mesa[] GetMesas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMesas", ReplyAction="http://tempuri.org/IService/GetMesasResponse")]
        System.Threading.Tasks.Task<RestauranteService.Mesa[]> GetMesasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSupervisores", ReplyAction="http://tempuri.org/IService/GetSupervisoresResponse")]
        RestauranteService.Supervisor[] GetSupervisores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSupervisores", ReplyAction="http://tempuri.org/IService/GetSupervisoresResponse")]
        System.Threading.Tasks.Task<RestauranteService.Supervisor[]> GetSupervisoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GenerarFactura", ReplyAction="http://tempuri.org/IService/GenerarFacturaResponse")]
        int GenerarFactura(RestauranteService.Factura factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GenerarFactura", ReplyAction="http://tempuri.org/IService/GenerarFacturaResponse")]
        System.Threading.Tasks.Task<int> GenerarFacturaAsync(RestauranteService.Factura factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DetalleFactura", ReplyAction="http://tempuri.org/IService/DetalleFacturaResponse")]
        string DetalleFactura(RestauranteService.DetallexFactura detallexFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DetalleFactura", ReplyAction="http://tempuri.org/IService/DetalleFacturaResponse")]
        System.Threading.Tasks.Task<string> DetalleFacturaAsync(RestauranteService.DetallexFactura detallexFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetVentasMesero", ReplyAction="http://tempuri.org/IService/GetVentasMeseroResponse")]
        RestauranteService.VentasMesero[] GetVentasMesero(System.DateTime fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetVentasMesero", ReplyAction="http://tempuri.org/IService/GetVentasMeseroResponse")]
        System.Threading.Tasks.Task<RestauranteService.VentasMesero[]> GetVentasMeseroAsync(System.DateTime fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetConsumosClientes", ReplyAction="http://tempuri.org/IService/GetConsumosClientesResponse")]
        RestauranteService.ConsumosClientes[] GetConsumosClientes(System.DateTime fechaInicio, int valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetConsumosClientes", ReplyAction="http://tempuri.org/IService/GetConsumosClientesResponse")]
        System.Threading.Tasks.Task<RestauranteService.ConsumosClientes[]> GetConsumosClientesAsync(System.DateTime fechaInicio, int valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductosTop", ReplyAction="http://tempuri.org/IService/GetProductosTopResponse")]
        RestauranteService.ProductoTop[] GetProductosTop(System.DateTime fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductosTop", ReplyAction="http://tempuri.org/IService/GetProductosTopResponse")]
        System.Threading.Tasks.Task<RestauranteService.ProductoTop[]> GetProductosTopAsync(System.DateTime fechaInicio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceChannel : RestauranteService.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RestauranteService.IService>, RestauranteService.IService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string RegistrarCliente(RestauranteService.Cliente cliente)
        {
            return base.Channel.RegistrarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarClienteAsync(RestauranteService.Cliente cliente)
        {
            return base.Channel.RegistrarClienteAsync(cliente);
        }
        
        public string RegistrarMesero(RestauranteService.Mesero mesero)
        {
            return base.Channel.RegistrarMesero(mesero);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarMeseroAsync(RestauranteService.Mesero mesero)
        {
            return base.Channel.RegistrarMeseroAsync(mesero);
        }
        
        public string RegistrarMesa(RestauranteService.Mesa mesa)
        {
            return base.Channel.RegistrarMesa(mesa);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarMesaAsync(RestauranteService.Mesa mesa)
        {
            return base.Channel.RegistrarMesaAsync(mesa);
        }
        
        public string RegistrarSupervisor(RestauranteService.Supervisor supervisor)
        {
            return base.Channel.RegistrarSupervisor(supervisor);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarSupervisorAsync(RestauranteService.Supervisor supervisor)
        {
            return base.Channel.RegistrarSupervisorAsync(supervisor);
        }
        
        public string ConsultaSupervisor(int IdSupervisor)
        {
            return base.Channel.ConsultaSupervisor(IdSupervisor);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaSupervisorAsync(int IdSupervisor)
        {
            return base.Channel.ConsultaSupervisorAsync(IdSupervisor);
        }
        
        public string ActualizarMesero(RestauranteService.Mesero mesero)
        {
            return base.Channel.ActualizarMesero(mesero);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarMeseroAsync(RestauranteService.Mesero mesero)
        {
            return base.Channel.ActualizarMeseroAsync(mesero);
        }
        
        public string ActualizarMesa(RestauranteService.Mesa mesa)
        {
            return base.Channel.ActualizarMesa(mesa);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarMesaAsync(RestauranteService.Mesa mesa)
        {
            return base.Channel.ActualizarMesaAsync(mesa);
        }
        
        public string ActualizarSupervisor(RestauranteService.Supervisor supervisor)
        {
            return base.Channel.ActualizarSupervisor(supervisor);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarSupervisorAsync(RestauranteService.Supervisor supervisor)
        {
            return base.Channel.ActualizarSupervisorAsync(supervisor);
        }
        
        public string EliminarMesero(RestauranteService.Mesero mesero)
        {
            return base.Channel.EliminarMesero(mesero);
        }
        
        public System.Threading.Tasks.Task<string> EliminarMeseroAsync(RestauranteService.Mesero mesero)
        {
            return base.Channel.EliminarMeseroAsync(mesero);
        }
        
        public string EliminarMesa(RestauranteService.Mesa mesa)
        {
            return base.Channel.EliminarMesa(mesa);
        }
        
        public System.Threading.Tasks.Task<string> EliminarMesaAsync(RestauranteService.Mesa mesa)
        {
            return base.Channel.EliminarMesaAsync(mesa);
        }
        
        public string EliminarSupervisor(RestauranteService.Supervisor supervisor)
        {
            return base.Channel.EliminarSupervisor(supervisor);
        }
        
        public System.Threading.Tasks.Task<string> EliminarSupervisorAsync(RestauranteService.Supervisor supervisor)
        {
            return base.Channel.EliminarSupervisorAsync(supervisor);
        }
        
        public RestauranteService.Mesero[] GetMeseros()
        {
            return base.Channel.GetMeseros();
        }
        
        public System.Threading.Tasks.Task<RestauranteService.Mesero[]> GetMeserosAsync()
        {
            return base.Channel.GetMeserosAsync();
        }
        
        public RestauranteService.Mesa[] GetMesas()
        {
            return base.Channel.GetMesas();
        }
        
        public System.Threading.Tasks.Task<RestauranteService.Mesa[]> GetMesasAsync()
        {
            return base.Channel.GetMesasAsync();
        }
        
        public RestauranteService.Supervisor[] GetSupervisores()
        {
            return base.Channel.GetSupervisores();
        }
        
        public System.Threading.Tasks.Task<RestauranteService.Supervisor[]> GetSupervisoresAsync()
        {
            return base.Channel.GetSupervisoresAsync();
        }
        
        public int GenerarFactura(RestauranteService.Factura factura)
        {
            return base.Channel.GenerarFactura(factura);
        }
        
        public System.Threading.Tasks.Task<int> GenerarFacturaAsync(RestauranteService.Factura factura)
        {
            return base.Channel.GenerarFacturaAsync(factura);
        }
        
        public string DetalleFactura(RestauranteService.DetallexFactura detallexFactura)
        {
            return base.Channel.DetalleFactura(detallexFactura);
        }
        
        public System.Threading.Tasks.Task<string> DetalleFacturaAsync(RestauranteService.DetallexFactura detallexFactura)
        {
            return base.Channel.DetalleFacturaAsync(detallexFactura);
        }
        
        public RestauranteService.VentasMesero[] GetVentasMesero(System.DateTime fechaInicio)
        {
            return base.Channel.GetVentasMesero(fechaInicio);
        }
        
        public System.Threading.Tasks.Task<RestauranteService.VentasMesero[]> GetVentasMeseroAsync(System.DateTime fechaInicio)
        {
            return base.Channel.GetVentasMeseroAsync(fechaInicio);
        }
        
        public RestauranteService.ConsumosClientes[] GetConsumosClientes(System.DateTime fechaInicio, int valor)
        {
            return base.Channel.GetConsumosClientes(fechaInicio, valor);
        }
        
        public System.Threading.Tasks.Task<RestauranteService.ConsumosClientes[]> GetConsumosClientesAsync(System.DateTime fechaInicio, int valor)
        {
            return base.Channel.GetConsumosClientesAsync(fechaInicio, valor);
        }
        
        public RestauranteService.ProductoTop[] GetProductosTop(System.DateTime fechaInicio)
        {
            return base.Channel.GetProductosTop(fechaInicio);
        }
        
        public System.Threading.Tasks.Task<RestauranteService.ProductoTop[]> GetProductosTopAsync(System.DateTime fechaInicio)
        {
            return base.Channel.GetProductosTopAsync(fechaInicio);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://70.37.99.231/Comidas_del_Sur_WS/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
